# Generated by Django 4.1 on 2023-02-04 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CheckList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateField(auto_created=True)),
                ("title", models.CharField(max_length=255)),
                ("completed", models.BooleanField()),
            ],
        ),
    ]
