# Generated by Django 4.1 on 2023-02-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checklist", "0006_remove_checklist_user_usermodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="phone",
            field=models.CharField(default=123456, max_length=10),
            preserve_default=False,
        ),
    ]
