# Generated by Django 4.1 on 2023-01-29 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentbio",
            name="DoB",
            field=models.DateField(
                default=datetime.datetime(2023, 1, 29, 15, 9, 51, 72301), null=True
            ),
        ),
    ]
