# Generated by Django 4.1 on 2023-01-29 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0003_alter_studentbio_dob"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentbio",
            name="DoB",
        ),
    ]
